# rob-slezak
# https://github.com/rob-slezak/course-material
# https://github.com/rob-slezak/assignment

language: node_js

node_js:
  - "10.9.0"

cache: npm

env:
  - NOW_TOKEN=TtP2Xse9sXwg2WfAh1ffBhyf

install:
  - npm install

script:
  - npm run build
  - npm run test

before_install:
  - mkdir public
  - "npm config set spin false"
  - npm i -g now

deploy:
  provider: script
  script: bash scripts/deploy.sh
  skip_cleanup: true
